---
title: "mixed model simulations"
date: '`r format(Sys.time(), "%d %b %Y")`'
output:
  html_document:
    code_folding: hide
---

Evaluating [Dale Barr's advice on maximal models](https://psyteachr.github.io/stat-models-v1/linear-mixed-effects-models-with-crossed-random-factors.html#rules-for-choosing-random-effects-for-categorical-factors). Modifying code by Mattan Ben-Shachar from [here](https://gist.github.com/mattansb/f18986b2b07e85c29a68b69c30881da3).

# Setup

```{r pkgs}
library(tidyverse)
theme_set(theme_bw(base_size=16))

library(faux)
library(lmerTest)
library(magrittr) ## for %$%
library(patchwork)
set.seed(101)
```

# Building up a complex design

```{r gen-data}
dta_design <-
  # 40 subjects
  add_random(subj = 40) |>
  # add design - each subject was measured on 4 conditions at 3 time points.
  add_within(
    "subj",
    time = c("pre", "post", "followup"),
    condition = c("cond1", "cond2", "cond3", "cond4")
  ) |>
  # effect coding
  add_contrast("time", contrast = "sum", 
               colnames = paste0("time", 1:2)) |>
  add_contrast("condition", contrast = "sum",
               colnames = paste0("condition", 1:3))

gen_data <- function() {
  dta_design |> 
    # random effects
    add_ranef("subj", 
              u0 = 1.5, 
              
              ut1 = 1.5,
              ut2 = 1.5,
              
              uc1 = 1.5, 
              uc2 = 1.5, 
              uc3 = 1.5,
              
              ui11 = 1.5,
              ui12 = 1.5,
              ui21 = 1.5,
              ui22 = 1.5,
              ui31 = 1.5,
              ui32 = 1.5,
              
              .cors = 0.3) |> 
    add_ranef(sigma = 2) |> 
    # compute DV - note that other than an average intercept of 3, there are NO
    # fixed effects.
    mutate(
      dv = (3 + u0) + 
        ut1 * time1 + ut2 * time2 + 
        (uc1 + ui11 * time1 + ui12 * time2) * condition1 + 
        (uc2 + ui21 * time1 + ui22 * time2) * condition2 + 
        (uc3 + ui31 * time1 + ui32 * time2) * condition3 + 
        sigma
    ) |> 
    select(subj:condition, dv)
}
```

```{r gen-data2}
## alternative data generator, uses lme4::simulate() to make sure
##  we match random effects model (although shouldn't matter?)
gen_data2 <- function() {
    ## construct sdcor matrix, convert to lme4 parameterization
    nn <- with(dta_design, 1 + (nlevels(time)-1) +
                           (nlevels(condition)-1))
    sdcormat <- matrix(0.3, nrow = nn, ncol = nn)
    diag(sdcormat) <- 1.5
    res_sd <- 2
    m <- t(chol(sdcor2cov(sdcormat))/res_sd)
    theta <- m[lower.tri(m, diag = TRUE)]
    ## now simulate ...
    dta_design |>
        mutate(dv = simulate( ~ 1 + (1 + time + condition | subj),
        newdata = dta_design,
        newparams = list(beta = 3,
                         theta = theta,
                         sigma = res_sd),
        family = gaussian)[[1]]) |>
        select(subj:condition, dv)
}
```


```{r check-nesting}
## make sure all subjects have 1 observation per cell:
## use magrittr 'exposition pipe' %$%
gen_data() |> 
    count(subj, time, condition) %$%
    stopifnot(all(n==1))
```

# Simulate

```{r simulate-define}
get_p_values <- function(tmp_data = gen_data(),
                         ddf = c("Satterthwaite", "Kenward-Roger"), ...) {
    ddf <- match.arg(ddf)
  
    ## the model recommended in 
    ##> https://psyteachr.github.io/stat-models-v1/linear-mixed-effects-models-with-crossed-random-factors.html#rules-for-choosing-random-effects-for-categorical-factors
    mod_random.intercept <- lmer(dv ~ time * condition + (1 | subj),
                                 data = tmp_data)
  
    mod_random.slope.time <- update(mod_random.intercept,
                                    . ~ . - (1 | subj) + (time | subj))
  
    mod_random.slope.condition <- update(mod_random.intercept,
                                    . ~ . - (1 | subj) + (condition | subj))
  
    ## the maximal model
    mod_random.slope.both <- update(mod_random.intercept,
                                    . ~ . - (1 | subj) + (time + condition | subj))
  
  list(
    "intercept only" = mod_random.intercept,
    "intercept + time" = mod_random.slope.time,
    "intercept + condition" = mod_random.slope.condition,
    "maximal: time + condition" = mod_random.slope.both
  ) |> 
    # get type 3 anova tables
    map(anova, type = 3, ddf = ddf) |> 
    # extract p-values
    map(parameters::p_value) |> 
    list_rbind(names_to = "model")
}


## not sure why .progress isn't working? do it myself ...
run_sim <- function(n = 50, data_fun = gen_data, ddf = "Satterthwaite", .progress = FALSE) {
    if (.progress) {
        pb <- txtProgressBar(style = 3, max = n)
        setpb <- function(n) setTxtProgressBar(pb, n)
    } else setpb <- function(n) {}
    suppressMessages(
        suppressWarnings(
            map(seq(n),  \(n) {setpb(n); get_p_values(data_fun(), ddf)}) |>
            list_rbind(names_to = "sim")
        )
    )
}
```

```{r simulate-run1, cache = TRUE}
set.seed(101)
t1 <- system.time(
    run1 <- run_sim(50)
)
```

```{r simulate-run2, cache = TRUE}
set.seed(101)
t2 <- system.time(
    run2 <- run_sim(50, gen_data2)
)
```

```{r simulate-run-KR, cache = TRUE}
set.seed(101)
t3 <- system.time(
    run2_kr <- run_sim(50, gen_data2, ddf = "Kenward-Roger")
)
```

# Plot results

compute type 1 error rates per effect and model specification

```{r summarize-plot}
alpha <- 0.05
sum_fun <- function(x) {
  s1 <- c(mean(x), binom.test(sum(x), length(x))$conf.int) |>
    setNames(c("type1_error", "lwr", "upr"))
  as_tibble(as.list(s1))
}

sum_run <- function(x) {
    x |> 
    mutate(across(c(model, Parameter), ~factor(., levels = unique(.)))) |>
        rename(Effect = "Parameter") |>
        summarise(
            sum_fun(p<alpha),
            .by = c(Effect, model)
        )
}

gg1 <- ggplot(sum_run(run1), aes(model, type1_error, color = Effect, shape = Effect)) + 
  geom_hline(yintercept = alpha, lty = 2) + 
  geom_pointrange(aes(ymin = lwr, ymax = upr),
                  position = position_dodge(0.7)) +
  expand_limits(y = 0) + 
  labs(
    x = "Random Effects Specification",
    color = "Fixed Effect",
    shape = "Fixed Effect",
    y = "type I error rate"    
  )

gg2 <- gg1 %+% sum_run(run2)
```

```{r show-plots, fig.height = 8, fig.width = 10}
## would do these side-by-side but labels get cramped (coord-flip??)
(gg1 + theme(legend.position = "none")) / gg2
```



